---
- name: Install MySQL, WordPress, Nginx and PHP-FPM
  hosts: fob
  become: yes

  vars_files:
    - group_vars/wordpress/vars
    - group_vars/wordpress/vault

  roles:
    - { role: common, tags: common }
    - { role: mysql, tags: mysql }
    - { role: php, tags: php }
    - { role: nginx, tags: nginx }
    - { role: wordpress, tags: wordpress }
