---
- name: Install PHP
  apt: name={{ item }} state=present
  with_items:
    - php-cli
    - php-curl
    - php-fpm
    - php-gd
    - php-mysql

- name: Start PHP5-FPM service
  service: name=php7.2-fpm.service state=started enabled=true
